import 'package:hive/hive.dart';

part 'expense.g.dart'; // Needed for Hive to generate the adapter code 
// This file will be generated by running the command: flutter packages pub run build_runner build

@HiveType(typeId: 0) // Unique ID for the Expense type in Hive
class Expense extends HiveObject {
  @HiveField(0)
  String title;

  @HiveField(1)
  double amount;

  @HiveField(2)
  DateTime date;
  
// Constructor to create a new expense
  Expense({required this.title, required this.amount, required this.date});
}

